### ISSUE TITLE
Constellations Summary & Rubric Score

### ISSUE THREAD

**Issue by karl-project-review** [smerlingcustodio/dvp-u3-constellations#1]
### Criteria 1: Matplotlib and CSV
* _Score Level:_ 4/4 (Exceeds Expectations) 
* _Comments:_ You imported all the necessary libraries.
### Criteria 2: Implementation of 2D Visualization
* _Score Level:_ 3/4 (Meets Expectations) 
* _Comments:_ You successfully created a 2D scatter plot of the data. Good work! However, consider adding a title to make it clear what this plot represents.
### Criteria 3: Implementation of 3D Visualization
* _Score Level:_ 4/4 (Exceeds Expectations) 
* _Comments:_ You created a rotatable, 3D plot of the constellation and included a descriptive title. Well done!
### Overall Score: 11/12 (Meets Expectations)
Nice work! You created both of the necessary visualizations. To make your plots even better, think about how we can use color selections to add more information. For example, if we assigned each star a unique color and used this same set of colors in both graphs, then we could easily match individual stars from the 2D plot to their 3D representations. Again, well done with this project!

**Comment by smerlingcustodio** [comment]
Thank You
